/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#4900e5',
        'primary-container': '#6236ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#e3dbff',
        secondary: '#b52330',
        'secondary-container': '#ff5a5f',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#60000e',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#484456',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#797488',
        'outline-variant': '#c9c3da',
        'surface-tint': '#5d2ffa',
        tertiary: '#484a5a',
        'tertiary-container': '#606273',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#dddff2',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
      },
      fontFamily: {
        montserrat: ['Montserrat', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        'level-2': '0px 4px 12px rgba(26,29,43,0.08)',
        'level-3': '0px 12px 32px rgba(26,29,43,0.15)',
      },
    },
  },
  plugins: [],
};
